//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusNabber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public System.Guid object_id { get; set; }
        public string company_name { get; set; }
        public string photo_path_160x600 { get; set; }
        public string photo_path_468x60 { get; set; }
        public string photo_path_728x90 { get; set; }
        public string photo_link { get; set; }
    }
}
