//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class FlagPost
{
    public System.Guid object_id { get; set; }
    public System.Guid flagged_postitem_id { get; set; }
    public string username_of_post { get; set; }
    public string flag_reason { get; set; }
    public string username_of_flagger { get; set; }
    public System.DateTime flag_date { get; set; }
}
