//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusNabber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid object_id { get; set; }
        public string username { get; set; }
        public byte[] encrypted_password { get; set; }
        public string student_email { get; set; }
        public string school_name { get; set; }
    }
}
